name: Deploy to S3 and Invalidate CloudFront

permissions:
  id-token: write # Required for OIDC
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Lint install and build dependencies
        run: |
          npm install
          npm run check
          VITE_BASE_URL=https://erikdunning.com npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-session-name: github-action-role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3 bucket
        run: |
          aws s3 sync ./build s3://${{ secrets.S3_BUCKET }}/build --delete
          echo "Files synced to S3 bucket"

      - name: Create CloudFront invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION }} --paths "/*"
          echo "CloudFront invalidation requested for distribution!"
